name = "CGMethod1D"
uuid = "1761bce2-f926-4d36-b6bd-cd0ee7bbe91e"
authors = ["Christian Garcia"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
